import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'AiKun',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="zh-cn">
      <body className="flex flex-col h-screen sm:max-w-sm mx-auto text-gray-300">{children}</body>
    </html>
  )
}
